# Generated by Django 5.2.12 on 2026-03-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(blank=True, default="website", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="source_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
