# Generated by Django 5.2.4 on 2026-03-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_source_fields"),
        ("cars", "0002_seed_cars"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lead request",
                "verbose_name_plural": "Lead requests",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="crm_external_id",
            field=models.CharField(
                blank=True,
                help_text="External CRM lead or deal identifier.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="crm_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last successful or attempted CRM sync timestamp.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="crm_sync_error",
            field=models.TextField(
                blank=True, help_text="Last CRM sync error payload or operator note."
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="crm_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                help_text="Current CRM synchronization state.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Optional email for consultation or support follow-up.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Free-form enquiry or support context from the site.",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                help_text="Preferred callback channel when one is provided.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("booking_request", "Booking request"),
                    ("contact_request", "Contact request"),
                    ("support_request", "Support request"),
                ],
                db_index=True,
                default="booking_request",
                help_text="Classifies the incoming lead intent.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewing", "Reviewing"),
                    ("contacted", "Contacted"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="new",
                help_text="Internal operator status for the lead.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                blank=True,
                help_text="Requested vehicle when the lead is a booking enquiry.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="cars.car",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Requested return date for booking enquiries.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(
                help_text="Primary customer or lead name.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number used for direct follow-up.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="website",
                help_text="Normalized entry source for attribution and CRM mapping.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured page, locale, and entry-point metadata from the frontend.",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Requested pickup date for booking enquiries.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["request_type", "status"], name="bookings_bo_request_11395f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["crm_sync_status", "created_at"],
                name="bookings_bo_crm_syn_28675e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["source", "created_at"], name="bookings_bo_source_679d97_idx"
            ),
        ),
    ]
