# Generated by Django 5.2.12 on 2026-03-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.URLField(blank=True)),
                ("description", models.TextField()),
                ("available", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
