# Generated by Django 5.2.12 on 2026-03-29 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_seed_cars"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["display_order", "brand", "model", "id"]},
        ),
        migrations.AddField(
            model_name="car",
            name="display_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Lower numbers appear first in the fleet and featured sections.",
                verbose_name="Display order",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload the main car image shown on the site.",
                upload_to="cars/",
                verbose_name="Primary image upload",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(
                default=True,
                help_text="Featured cars are prioritized on the homepage.",
                verbose_name="Featured on home page",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Turn this off to keep the car in admin while hiding it from visitors.",
                verbose_name="Visible on public site",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="long_description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional extended description used on the car detail page.",
                verbose_name="Long description (English)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="long_description_ru",
            field=models.TextField(
                blank=True,
                help_text="Optional extended description used on the car detail page.",
                verbose_name="Long description (Russian)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="short_description_en",
            field=models.TextField(
                blank=True,
                help_text="Shown on cards and summary areas.",
                verbose_name="Short description (English)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="short_description_ru",
            field=models.TextField(
                blank=True,
                help_text="Shown on cards and summary areas.",
                verbose_name="Short description (Russian)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Optional public title. Leave blank to show Brand + Model.",
                max_length=255,
                verbose_name="Marketing title (English)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="title_ru",
            field=models.CharField(
                blank=True,
                help_text="Optional public title. Leave blank to show Brand + Model.",
                max_length=255,
                verbose_name="Marketing title (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="available",
            field=models.BooleanField(
                default=True, verbose_name="Available for booking"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="Brand"),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Legacy fallback description kept so existing content remains visible.",
                verbose_name="Legacy description",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="Existing public image URL kept for backwards-compatible fallbacks.",
                max_length=500,
                verbose_name="Legacy image URL",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="price_per_day",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price per day"
            ),
        ),
        migrations.CreateModel(
            name="CarGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first on the public site.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Turn this off to hide the item from the public fleet without deleting it.",
                        verbose_name="Visible on site",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        upload_to="cars/gallery/",
                        verbose_name="Gallery image upload",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional external image URL used when no upload is provided.",
                        max_length=500,
                        verbose_name="Gallery image URL",
                    ),
                ),
                (
                    "alt_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt text (English)"
                    ),
                ),
                (
                    "alt_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt text (Russian)"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car gallery image",
                "verbose_name_plural": "Car gallery images",
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
    ]
